version: 2
jobs:
  build: 
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - setup_remote_docker
      - run: docker login -u $docker_username -p $docker_password
      - run: 
          name: Build and push docker images
          command: |
              cp Dockerfile.production Dockerfile
              docker build -t worrathep/example-nodejs-express:latest .
              docker build -t worrathep/example-nodejs-express:${CIRCLE_SHA1} .
              docker push worrathep/example-nodejs-express:latest
              docker push worrathep/example-nodejs-express:${CIRCLE_SHA1}
  test: 
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build  
      - test2:
          requires:
            - test1 
      - deploy:
          requires:
            - test2